### ISSUE TITLE
Tag releases on git and manage a changelog (using GitHub releases?)

### ISSUE THREAD

**Issue by yvele** [rowanwins/shamos-hoey#13]
Hi, thank you for your amazing library ✋ 

When you make a new release on npm, can you also tag releases on git?

Using GitHub release may also be super useful to handle and manage the git tags along with changelogs.

As an example see other OSS projects like (I'm picking them randomly)
 - https://github.com/chalk/chalk/releases
 - https://github.com/tjunnone/npm-check-updates/releases
 - https://github.com/babel/babel/releases
 - etc.

You may also have a look at https://semver.org for semantic versioning

**Comment by rowanwins** [comment]
Yeah thanks for the suggestion @yvele - I typically follow semver for releases but I'm pretty slack with tagging releases and doing change logs when I'm running hobby projects, I'll try and improve though :)

**Comment by rowanwins** [comment]
Have added a CHANGES.md and pushed a tag on my latest release

**Comment by yvele** [comment]
Awesome! Thank you.

Also I suggest renaming `CHANGES.md` to `CHANGELOG.md` as it is more "common" and then easier to find.

Edit: `CHANGES` / `CHANGELOG` / `HISTORY` are all "standard" but in majority of open source projects, looks like `CHANGELOG.md` is commonly used 🤔

**Comment by rowanwins** [comment]
Yeah I've both CHANGELOG and CHANGES in use, can't say I've noticed HISTORY much.
