### ISSUE TITLE
Some polygons produce false negatives

### ISSUE THREAD

**Issue by av2k** [rowanwins/shamos-hoey#2]
Hello,

thanks for providing this valuable algorithm!

I get some false negatives here, e.g. 

[{"x":233,"y":115},{"x":190,"y":186},{"x":247,"y":260},{"x":430,"y":304},{"x":531,"y":244},{"x":510,"y":170},{"x":415,"y":104},{"x":553,"y":196}]

Please let me know if I can help debugging.

Here is another polygon with comparable coordinates.

![grafik](https://user-images.githubusercontent.com/8684223/52503990-6563f480-2be7-11e9-98e3-44f87b75b078.png)

**Comment by rowanwins** [comment]
Thanks forthe report @av2k , I'll take a look into things and report back

**Comment by rowanwins** [comment]
Hi @av2k 

I've just published v0.0.7 which resolves this issue, I think the basic problem was that the final segment was not being checked.

**Comment by av2k** [comment]
Hello, that's great!

Apparently there seems to be either another issue or I am doing something wrong.

For example with

[{"x":279,"y":160},{"x":193,"y":313},{"x":193,"y":363},{"x":253,"y":414},{"x":331,"y":443},{"x":456,"y":419},{"x":490,"y":337},{"x":470,"y":290},{"x":395,"y":346},{"x":357,"y":370},{"x":292,"y":363},{"x":260,"y":328},{"x":279,"y":275},{"x":350,"y":233},{"x":408,"y":155},{"x":361,"y":128},{"x":157,"y":367}]

![grafik](https://user-images.githubusercontent.com/8684223/52533847-42962500-2d3a-11e9-9a38-d49166121a4f.png)

the edge V15/V16 cuts the edge V1/V2.

Maybe I should note that sometimes, there also occurs an infinite recursion during a search operation, but I could not yet figure out the cause as the browser hangs up when it happens.

**Comment by av2k** [comment]
Here is another one:

[{"x":217,"y":256},{"x":211,"y":324},{"x":226,"y":359},{"x":297,"y":387},{"x":498,"y":392},{"x":698,"y":350},{"x":763,"y":229},{"x":721,"y":170},{"x":507,"y":111},{"x":489,"y":130},{"x":503,"y":167},{"x":539,"y":206},{"x":562,"y":239},{"x":576,"y":262},{"x":574,"y":291},{"x":549,"y":309},{"x":480,"y":331},{"x":433,"y":338},{"x":378,"y":331},{"x":344,"y":300},{"x":341,"y":265},{"x":374,"y":234},{"x":481,"y":192},{"x":459,"y":166},{"x":440,"y":145},{"x":425,"y":129},{"x":407,"y":114},{"x":388,"y":114},{"x":349,"y":121},{"x":313,"y":131},{"x":287,"y":140},{"x":256,"y":150},{"x":226,"y":160},{"x":192,"y":177},{"x":169,"y":191},{"x":159,"y":216},{"x":170,"y":251},{"x":511,"y":82}]

![grafik](https://user-images.githubusercontent.com/8684223/52534408-70cb3300-2d41-11e9-8eb0-9bdb5f0931eb.png)

I can only errorneously insert a new node (which will have two edges to V0 and V36) between V22 and V26, but neigher left of V26 (V27, V28, ...) nor below V22 (V21, V20, ...).

However, I can also get an errorneous result if the newly-added V37 has to cross the edge V34-V35 to get to V0.

[{"x":217,"y":256},{"x":211,"y":324},{"x":226,"y":359},{"x":297,"y":387},{"x":498,"y":392},{"x":698,"y":350},{"x":763,"y":229},{"x":721,"y":170},{"x":507,"y":111},{"x":489,"y":130},{"x":503,"y":167},{"x":539,"y":206},{"x":562,"y":239},{"x":576,"y":262},{"x":574,"y":291},{"x":549,"y":309},{"x":480,"y":331},{"x":433,"y":338},{"x":378,"y":331},{"x":344,"y":300},{"x":341,"y":265},{"x":374,"y":234},{"x":481,"y":192},{"x":459,"y":166},{"x":440,"y":145},{"x":425,"y":129},{"x":407,"y":114},{"x":388,"y":114},{"x":349,"y":121},{"x":313,"y":131},{"x":287,"y":140},{"x":256,"y":150},{"x":226,"y":160},{"x":192,"y":177},{"x":169,"y":191},{"x":159,"y":216},{"x":170,"y":251},{"x":459,"y":113}]

![grafik](https://user-images.githubusercontent.com/8684223/52534413-7de82200-2d41-11e9-929c-e3796cbf81e8.png)

[{"x":217,"y":256},{"x":211,"y":324},{"x":226,"y":359},{"x":297,"y":387},{"x":498,"y":392},{"x":698,"y":350},{"x":763,"y":229},{"x":721,"y":170},{"x":507,"y":111},{"x":489,"y":130},{"x":503,"y":167},{"x":539,"y":206},{"x":562,"y":239},{"x":576,"y":262},{"x":574,"y":291},{"x":549,"y":309},{"x":480,"y":331},{"x":433,"y":338},{"x":378,"y":331},{"x":344,"y":300},{"x":341,"y":265},{"x":374,"y":234},{"x":481,"y":192},{"x":459,"y":166},{"x":440,"y":145},{"x":425,"y":129},{"x":407,"y":114},{"x":388,"y":114},{"x":349,"y":121},{"x":313,"y":131},{"x":287,"y":140},{"x":256,"y":150},{"x":226,"y":160},{"x":192,"y":177},{"x":169,"y":191},{"x":159,"y":216},{"x":172,"y":252},{"x":142,"y":183}]
![grafik](https://user-images.githubusercontent.com/8684223/52534469-1088c100-2d42-11e9-9599-aac8e78400e3.png)

I've marked the possible areas for an errorneous insertion of a node that is connected to V36 and V0 in red, so, V37 could be anywhere in the red area and it would result in a false positive "isSimple".

![grafik](https://user-images.githubusercontent.com/8684223/52534483-4463e680-2d42-11e9-8131-1422e37f57d8.png)

**Comment by rowanwins** [comment]
Hi @av2k 

The first case appears to be working (see [this runkit](https://runkit.com/rowanwins/shamos-hoey))

However the cases in your last comment do appear to be broken...

**Comment by rowanwins** [comment]
Hi @av2k 

I've reworked the segment comparison and i think its now fixed... fingers crossed! Released as v0.0.9

**Comment by av2k** [comment]
Thanks! Very good. It seems to be working flawlessly now.
