### ISSUE TITLE
Get error with 'ReferenceError: L is not defined'

### ISSUE THREAD

**Issue by fc** [rowanwins/shamos-hoey#4]
It appears the distributed package contains a call to a debug call?
![image](https://user-images.githubusercontent.com/20962/70950318-0fd15300-2015-11ea-98e1-f40121420b74.png)

It appears the cause is because in the package.json this line exists:
```
  "module": "src/main.js",
```
So instead of using the bundled version, it uses that instead which means it will execute the debug functions.  In the compiled version, the rollup config is stripping out that function.

Anyway... the right the thing to do seems to be to probably remove that line in the package.json.

**Comment by fc** [comment]
Also, if someone needs a workaround, you may import like so:
```
import isNotSelfIntersecting from 'shamos-hoey/dist/shamosHoey.min';
```

**Comment by rowanwins** [comment]
Thanks for reporting @fc , good pickup and workaround!

**Comment by rowanwins** [comment]
The other option is to create another bundle using rollup using `format: esm` and point the `module`.

**Comment by rowanwins** [comment]
Resolved by https://github.com/rowanwins/shamos-hoey/commit/a4aed459c1c8d5e0cd7255e584d82e5de8730cd9
